name = "echo_server"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.36"
glisten = { path = "../../" }
gleam_erlang = "~> 0.24"
gleam_otp = "~> 0.9"
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
